// Code generated by ent, DO NOT EDIT.

package openuem_ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/doncicuto/openuem_ent/agent"
	"github.com/doncicuto/openuem_ent/antivirus"
	"github.com/doncicuto/openuem_ent/app"
	"github.com/doncicuto/openuem_ent/computer"
	"github.com/doncicuto/openuem_ent/deployment"
	"github.com/doncicuto/openuem_ent/logicaldisk"
	"github.com/doncicuto/openuem_ent/monitor"
	"github.com/doncicuto/openuem_ent/networkadapter"
	"github.com/doncicuto/openuem_ent/operatingsystem"
	"github.com/doncicuto/openuem_ent/predicate"
	"github.com/doncicuto/openuem_ent/printer"
	"github.com/doncicuto/openuem_ent/share"
	"github.com/doncicuto/openuem_ent/systemupdate"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks     []Hook
	mutation  *AgentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AgentUpdate builder.
func (au *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetOs sets the "os" field.
func (au *AgentUpdate) SetOs(s string) *AgentUpdate {
	au.mutation.SetOs(s)
	return au
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (au *AgentUpdate) SetNillableOs(s *string) *AgentUpdate {
	if s != nil {
		au.SetOs(*s)
	}
	return au
}

// SetHostname sets the "hostname" field.
func (au *AgentUpdate) SetHostname(s string) *AgentUpdate {
	au.mutation.SetHostname(s)
	return au
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (au *AgentUpdate) SetNillableHostname(s *string) *AgentUpdate {
	if s != nil {
		au.SetHostname(*s)
	}
	return au
}

// SetVersion sets the "version" field.
func (au *AgentUpdate) SetVersion(s string) *AgentUpdate {
	au.mutation.SetVersion(s)
	return au
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (au *AgentUpdate) SetNillableVersion(s *string) *AgentUpdate {
	if s != nil {
		au.SetVersion(*s)
	}
	return au
}

// SetIP sets the "ip" field.
func (au *AgentUpdate) SetIP(s string) *AgentUpdate {
	au.mutation.SetIP(s)
	return au
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (au *AgentUpdate) SetNillableIP(s *string) *AgentUpdate {
	if s != nil {
		au.SetIP(*s)
	}
	return au
}

// SetFirstContact sets the "first_contact" field.
func (au *AgentUpdate) SetFirstContact(t time.Time) *AgentUpdate {
	au.mutation.SetFirstContact(t)
	return au
}

// SetNillableFirstContact sets the "first_contact" field if the given value is not nil.
func (au *AgentUpdate) SetNillableFirstContact(t *time.Time) *AgentUpdate {
	if t != nil {
		au.SetFirstContact(*t)
	}
	return au
}

// ClearFirstContact clears the value of the "first_contact" field.
func (au *AgentUpdate) ClearFirstContact() *AgentUpdate {
	au.mutation.ClearFirstContact()
	return au
}

// SetLastContact sets the "last_contact" field.
func (au *AgentUpdate) SetLastContact(t time.Time) *AgentUpdate {
	au.mutation.SetLastContact(t)
	return au
}

// SetNillableLastContact sets the "last_contact" field if the given value is not nil.
func (au *AgentUpdate) SetNillableLastContact(t *time.Time) *AgentUpdate {
	if t != nil {
		au.SetLastContact(*t)
	}
	return au
}

// ClearLastContact clears the value of the "last_contact" field.
func (au *AgentUpdate) ClearLastContact() *AgentUpdate {
	au.mutation.ClearLastContact()
	return au
}

// SetEnabled sets the "enabled" field.
func (au *AgentUpdate) SetEnabled(b bool) *AgentUpdate {
	au.mutation.SetEnabled(b)
	return au
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (au *AgentUpdate) SetNillableEnabled(b *bool) *AgentUpdate {
	if b != nil {
		au.SetEnabled(*b)
	}
	return au
}

// SetVnc sets the "vnc" field.
func (au *AgentUpdate) SetVnc(s string) *AgentUpdate {
	au.mutation.SetVnc(s)
	return au
}

// SetNillableVnc sets the "vnc" field if the given value is not nil.
func (au *AgentUpdate) SetNillableVnc(s *string) *AgentUpdate {
	if s != nil {
		au.SetVnc(*s)
	}
	return au
}

// ClearVnc clears the value of the "vnc" field.
func (au *AgentUpdate) ClearVnc() *AgentUpdate {
	au.mutation.ClearVnc()
	return au
}

// SetComputerID sets the "computer" edge to the Computer entity by ID.
func (au *AgentUpdate) SetComputerID(id int) *AgentUpdate {
	au.mutation.SetComputerID(id)
	return au
}

// SetNillableComputerID sets the "computer" edge to the Computer entity by ID if the given value is not nil.
func (au *AgentUpdate) SetNillableComputerID(id *int) *AgentUpdate {
	if id != nil {
		au = au.SetComputerID(*id)
	}
	return au
}

// SetComputer sets the "computer" edge to the Computer entity.
func (au *AgentUpdate) SetComputer(c *Computer) *AgentUpdate {
	return au.SetComputerID(c.ID)
}

// SetOperatingsystemID sets the "operatingsystem" edge to the OperatingSystem entity by ID.
func (au *AgentUpdate) SetOperatingsystemID(id int) *AgentUpdate {
	au.mutation.SetOperatingsystemID(id)
	return au
}

// SetNillableOperatingsystemID sets the "operatingsystem" edge to the OperatingSystem entity by ID if the given value is not nil.
func (au *AgentUpdate) SetNillableOperatingsystemID(id *int) *AgentUpdate {
	if id != nil {
		au = au.SetOperatingsystemID(*id)
	}
	return au
}

// SetOperatingsystem sets the "operatingsystem" edge to the OperatingSystem entity.
func (au *AgentUpdate) SetOperatingsystem(o *OperatingSystem) *AgentUpdate {
	return au.SetOperatingsystemID(o.ID)
}

// SetSystemupdateID sets the "systemupdate" edge to the SystemUpdate entity by ID.
func (au *AgentUpdate) SetSystemupdateID(id int) *AgentUpdate {
	au.mutation.SetSystemupdateID(id)
	return au
}

// SetNillableSystemupdateID sets the "systemupdate" edge to the SystemUpdate entity by ID if the given value is not nil.
func (au *AgentUpdate) SetNillableSystemupdateID(id *int) *AgentUpdate {
	if id != nil {
		au = au.SetSystemupdateID(*id)
	}
	return au
}

// SetSystemupdate sets the "systemupdate" edge to the SystemUpdate entity.
func (au *AgentUpdate) SetSystemupdate(s *SystemUpdate) *AgentUpdate {
	return au.SetSystemupdateID(s.ID)
}

// SetAntivirusID sets the "antivirus" edge to the Antivirus entity by ID.
func (au *AgentUpdate) SetAntivirusID(id int) *AgentUpdate {
	au.mutation.SetAntivirusID(id)
	return au
}

// SetNillableAntivirusID sets the "antivirus" edge to the Antivirus entity by ID if the given value is not nil.
func (au *AgentUpdate) SetNillableAntivirusID(id *int) *AgentUpdate {
	if id != nil {
		au = au.SetAntivirusID(*id)
	}
	return au
}

// SetAntivirus sets the "antivirus" edge to the Antivirus entity.
func (au *AgentUpdate) SetAntivirus(a *Antivirus) *AgentUpdate {
	return au.SetAntivirusID(a.ID)
}

// AddLogicaldiskIDs adds the "logicaldisks" edge to the LogicalDisk entity by IDs.
func (au *AgentUpdate) AddLogicaldiskIDs(ids ...int) *AgentUpdate {
	au.mutation.AddLogicaldiskIDs(ids...)
	return au
}

// AddLogicaldisks adds the "logicaldisks" edges to the LogicalDisk entity.
func (au *AgentUpdate) AddLogicaldisks(l ...*LogicalDisk) *AgentUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return au.AddLogicaldiskIDs(ids...)
}

// AddAppIDs adds the "apps" edge to the App entity by IDs.
func (au *AgentUpdate) AddAppIDs(ids ...int) *AgentUpdate {
	au.mutation.AddAppIDs(ids...)
	return au
}

// AddApps adds the "apps" edges to the App entity.
func (au *AgentUpdate) AddApps(a ...*App) *AgentUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.AddAppIDs(ids...)
}

// AddMonitorIDs adds the "monitors" edge to the Monitor entity by IDs.
func (au *AgentUpdate) AddMonitorIDs(ids ...int) *AgentUpdate {
	au.mutation.AddMonitorIDs(ids...)
	return au
}

// AddMonitors adds the "monitors" edges to the Monitor entity.
func (au *AgentUpdate) AddMonitors(m ...*Monitor) *AgentUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return au.AddMonitorIDs(ids...)
}

// AddShareIDs adds the "shares" edge to the Share entity by IDs.
func (au *AgentUpdate) AddShareIDs(ids ...int) *AgentUpdate {
	au.mutation.AddShareIDs(ids...)
	return au
}

// AddShares adds the "shares" edges to the Share entity.
func (au *AgentUpdate) AddShares(s ...*Share) *AgentUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return au.AddShareIDs(ids...)
}

// AddPrinterIDs adds the "printers" edge to the Printer entity by IDs.
func (au *AgentUpdate) AddPrinterIDs(ids ...int) *AgentUpdate {
	au.mutation.AddPrinterIDs(ids...)
	return au
}

// AddPrinters adds the "printers" edges to the Printer entity.
func (au *AgentUpdate) AddPrinters(p ...*Printer) *AgentUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return au.AddPrinterIDs(ids...)
}

// AddNetworkadapterIDs adds the "networkadapters" edge to the NetworkAdapter entity by IDs.
func (au *AgentUpdate) AddNetworkadapterIDs(ids ...int) *AgentUpdate {
	au.mutation.AddNetworkadapterIDs(ids...)
	return au
}

// AddNetworkadapters adds the "networkadapters" edges to the NetworkAdapter entity.
func (au *AgentUpdate) AddNetworkadapters(n ...*NetworkAdapter) *AgentUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return au.AddNetworkadapterIDs(ids...)
}

// AddDeploymentIDs adds the "deployments" edge to the Deployment entity by IDs.
func (au *AgentUpdate) AddDeploymentIDs(ids ...int) *AgentUpdate {
	au.mutation.AddDeploymentIDs(ids...)
	return au
}

// AddDeployments adds the "deployments" edges to the Deployment entity.
func (au *AgentUpdate) AddDeployments(d ...*Deployment) *AgentUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return au.AddDeploymentIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (au *AgentUpdate) Mutation() *AgentMutation {
	return au.mutation
}

// ClearComputer clears the "computer" edge to the Computer entity.
func (au *AgentUpdate) ClearComputer() *AgentUpdate {
	au.mutation.ClearComputer()
	return au
}

// ClearOperatingsystem clears the "operatingsystem" edge to the OperatingSystem entity.
func (au *AgentUpdate) ClearOperatingsystem() *AgentUpdate {
	au.mutation.ClearOperatingsystem()
	return au
}

// ClearSystemupdate clears the "systemupdate" edge to the SystemUpdate entity.
func (au *AgentUpdate) ClearSystemupdate() *AgentUpdate {
	au.mutation.ClearSystemupdate()
	return au
}

// ClearAntivirus clears the "antivirus" edge to the Antivirus entity.
func (au *AgentUpdate) ClearAntivirus() *AgentUpdate {
	au.mutation.ClearAntivirus()
	return au
}

// ClearLogicaldisks clears all "logicaldisks" edges to the LogicalDisk entity.
func (au *AgentUpdate) ClearLogicaldisks() *AgentUpdate {
	au.mutation.ClearLogicaldisks()
	return au
}

// RemoveLogicaldiskIDs removes the "logicaldisks" edge to LogicalDisk entities by IDs.
func (au *AgentUpdate) RemoveLogicaldiskIDs(ids ...int) *AgentUpdate {
	au.mutation.RemoveLogicaldiskIDs(ids...)
	return au
}

// RemoveLogicaldisks removes "logicaldisks" edges to LogicalDisk entities.
func (au *AgentUpdate) RemoveLogicaldisks(l ...*LogicalDisk) *AgentUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return au.RemoveLogicaldiskIDs(ids...)
}

// ClearApps clears all "apps" edges to the App entity.
func (au *AgentUpdate) ClearApps() *AgentUpdate {
	au.mutation.ClearApps()
	return au
}

// RemoveAppIDs removes the "apps" edge to App entities by IDs.
func (au *AgentUpdate) RemoveAppIDs(ids ...int) *AgentUpdate {
	au.mutation.RemoveAppIDs(ids...)
	return au
}

// RemoveApps removes "apps" edges to App entities.
func (au *AgentUpdate) RemoveApps(a ...*App) *AgentUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.RemoveAppIDs(ids...)
}

// ClearMonitors clears all "monitors" edges to the Monitor entity.
func (au *AgentUpdate) ClearMonitors() *AgentUpdate {
	au.mutation.ClearMonitors()
	return au
}

// RemoveMonitorIDs removes the "monitors" edge to Monitor entities by IDs.
func (au *AgentUpdate) RemoveMonitorIDs(ids ...int) *AgentUpdate {
	au.mutation.RemoveMonitorIDs(ids...)
	return au
}

// RemoveMonitors removes "monitors" edges to Monitor entities.
func (au *AgentUpdate) RemoveMonitors(m ...*Monitor) *AgentUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return au.RemoveMonitorIDs(ids...)
}

// ClearShares clears all "shares" edges to the Share entity.
func (au *AgentUpdate) ClearShares() *AgentUpdate {
	au.mutation.ClearShares()
	return au
}

// RemoveShareIDs removes the "shares" edge to Share entities by IDs.
func (au *AgentUpdate) RemoveShareIDs(ids ...int) *AgentUpdate {
	au.mutation.RemoveShareIDs(ids...)
	return au
}

// RemoveShares removes "shares" edges to Share entities.
func (au *AgentUpdate) RemoveShares(s ...*Share) *AgentUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return au.RemoveShareIDs(ids...)
}

// ClearPrinters clears all "printers" edges to the Printer entity.
func (au *AgentUpdate) ClearPrinters() *AgentUpdate {
	au.mutation.ClearPrinters()
	return au
}

// RemovePrinterIDs removes the "printers" edge to Printer entities by IDs.
func (au *AgentUpdate) RemovePrinterIDs(ids ...int) *AgentUpdate {
	au.mutation.RemovePrinterIDs(ids...)
	return au
}

// RemovePrinters removes "printers" edges to Printer entities.
func (au *AgentUpdate) RemovePrinters(p ...*Printer) *AgentUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return au.RemovePrinterIDs(ids...)
}

// ClearNetworkadapters clears all "networkadapters" edges to the NetworkAdapter entity.
func (au *AgentUpdate) ClearNetworkadapters() *AgentUpdate {
	au.mutation.ClearNetworkadapters()
	return au
}

// RemoveNetworkadapterIDs removes the "networkadapters" edge to NetworkAdapter entities by IDs.
func (au *AgentUpdate) RemoveNetworkadapterIDs(ids ...int) *AgentUpdate {
	au.mutation.RemoveNetworkadapterIDs(ids...)
	return au
}

// RemoveNetworkadapters removes "networkadapters" edges to NetworkAdapter entities.
func (au *AgentUpdate) RemoveNetworkadapters(n ...*NetworkAdapter) *AgentUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return au.RemoveNetworkadapterIDs(ids...)
}

// ClearDeployments clears all "deployments" edges to the Deployment entity.
func (au *AgentUpdate) ClearDeployments() *AgentUpdate {
	au.mutation.ClearDeployments()
	return au
}

// RemoveDeploymentIDs removes the "deployments" edge to Deployment entities by IDs.
func (au *AgentUpdate) RemoveDeploymentIDs(ids ...int) *AgentUpdate {
	au.mutation.RemoveDeploymentIDs(ids...)
	return au
}

// RemoveDeployments removes "deployments" edges to Deployment entities.
func (au *AgentUpdate) RemoveDeployments(d ...*Deployment) *AgentUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return au.RemoveDeploymentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AgentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AgentUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AgentUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AgentUpdate) check() error {
	if v, ok := au.mutation.Os(); ok {
		if err := agent.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`openuem_ent: validator failed for field "Agent.os": %w`, err)}
		}
	}
	if v, ok := au.mutation.Hostname(); ok {
		if err := agent.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`openuem_ent: validator failed for field "Agent.hostname": %w`, err)}
		}
	}
	if v, ok := au.mutation.Version(); ok {
		if err := agent.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`openuem_ent: validator failed for field "Agent.version": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (au *AgentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AgentUpdate {
	au.modifiers = append(au.modifiers, modifiers...)
	return au
}

func (au *AgentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Os(); ok {
		_spec.SetField(agent.FieldOs, field.TypeString, value)
	}
	if value, ok := au.mutation.Hostname(); ok {
		_spec.SetField(agent.FieldHostname, field.TypeString, value)
	}
	if value, ok := au.mutation.Version(); ok {
		_spec.SetField(agent.FieldVersion, field.TypeString, value)
	}
	if value, ok := au.mutation.IP(); ok {
		_spec.SetField(agent.FieldIP, field.TypeString, value)
	}
	if value, ok := au.mutation.FirstContact(); ok {
		_spec.SetField(agent.FieldFirstContact, field.TypeTime, value)
	}
	if au.mutation.FirstContactCleared() {
		_spec.ClearField(agent.FieldFirstContact, field.TypeTime)
	}
	if value, ok := au.mutation.LastContact(); ok {
		_spec.SetField(agent.FieldLastContact, field.TypeTime, value)
	}
	if au.mutation.LastContactCleared() {
		_spec.ClearField(agent.FieldLastContact, field.TypeTime)
	}
	if value, ok := au.mutation.Enabled(); ok {
		_spec.SetField(agent.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := au.mutation.Vnc(); ok {
		_spec.SetField(agent.FieldVnc, field.TypeString, value)
	}
	if au.mutation.VncCleared() {
		_spec.ClearField(agent.FieldVnc, field.TypeString)
	}
	if au.mutation.ComputerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.ComputerTable,
			Columns: []string{agent.ComputerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(computer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.ComputerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.ComputerTable,
			Columns: []string{agent.ComputerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(computer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.OperatingsystemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.OperatingsystemTable,
			Columns: []string{agent.OperatingsystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatingsystem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.OperatingsystemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.OperatingsystemTable,
			Columns: []string{agent.OperatingsystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatingsystem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.SystemupdateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.SystemupdateTable,
			Columns: []string{agent.SystemupdateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemupdate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.SystemupdateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.SystemupdateTable,
			Columns: []string{agent.SystemupdateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemupdate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.AntivirusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.AntivirusTable,
			Columns: []string{agent.AntivirusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(antivirus.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.AntivirusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.AntivirusTable,
			Columns: []string{agent.AntivirusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(antivirus.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.LogicaldisksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.LogicaldisksTable,
			Columns: []string{agent.LogicaldisksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logicaldisk.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedLogicaldisksIDs(); len(nodes) > 0 && !au.mutation.LogicaldisksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.LogicaldisksTable,
			Columns: []string{agent.LogicaldisksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logicaldisk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.LogicaldisksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.LogicaldisksTable,
			Columns: []string{agent.LogicaldisksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logicaldisk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.AppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AppsTable,
			Columns: []string{agent.AppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedAppsIDs(); len(nodes) > 0 && !au.mutation.AppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AppsTable,
			Columns: []string{agent.AppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.AppsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AppsTable,
			Columns: []string{agent.AppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.MonitorsTable,
			Columns: []string{agent.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedMonitorsIDs(); len(nodes) > 0 && !au.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.MonitorsTable,
			Columns: []string{agent.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.MonitorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.MonitorsTable,
			Columns: []string{agent.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SharesTable,
			Columns: []string{agent.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedSharesIDs(); len(nodes) > 0 && !au.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SharesTable,
			Columns: []string{agent.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SharesTable,
			Columns: []string{agent.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.PrintersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.PrintersTable,
			Columns: []string{agent.PrintersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(printer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedPrintersIDs(); len(nodes) > 0 && !au.mutation.PrintersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.PrintersTable,
			Columns: []string{agent.PrintersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(printer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.PrintersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.PrintersTable,
			Columns: []string{agent.PrintersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(printer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.NetworkadaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.NetworkadaptersTable,
			Columns: []string{agent.NetworkadaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkadapter.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedNetworkadaptersIDs(); len(nodes) > 0 && !au.mutation.NetworkadaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.NetworkadaptersTable,
			Columns: []string{agent.NetworkadaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkadapter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.NetworkadaptersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.NetworkadaptersTable,
			Columns: []string{agent.NetworkadaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkadapter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.DeploymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.DeploymentsTable,
			Columns: []string{agent.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedDeploymentsIDs(); len(nodes) > 0 && !au.mutation.DeploymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.DeploymentsTable,
			Columns: []string{agent.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.DeploymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.DeploymentsTable,
			Columns: []string{agent.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(au.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AgentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetOs sets the "os" field.
func (auo *AgentUpdateOne) SetOs(s string) *AgentUpdateOne {
	auo.mutation.SetOs(s)
	return auo
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableOs(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetOs(*s)
	}
	return auo
}

// SetHostname sets the "hostname" field.
func (auo *AgentUpdateOne) SetHostname(s string) *AgentUpdateOne {
	auo.mutation.SetHostname(s)
	return auo
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableHostname(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetHostname(*s)
	}
	return auo
}

// SetVersion sets the "version" field.
func (auo *AgentUpdateOne) SetVersion(s string) *AgentUpdateOne {
	auo.mutation.SetVersion(s)
	return auo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableVersion(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetVersion(*s)
	}
	return auo
}

// SetIP sets the "ip" field.
func (auo *AgentUpdateOne) SetIP(s string) *AgentUpdateOne {
	auo.mutation.SetIP(s)
	return auo
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableIP(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetIP(*s)
	}
	return auo
}

// SetFirstContact sets the "first_contact" field.
func (auo *AgentUpdateOne) SetFirstContact(t time.Time) *AgentUpdateOne {
	auo.mutation.SetFirstContact(t)
	return auo
}

// SetNillableFirstContact sets the "first_contact" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableFirstContact(t *time.Time) *AgentUpdateOne {
	if t != nil {
		auo.SetFirstContact(*t)
	}
	return auo
}

// ClearFirstContact clears the value of the "first_contact" field.
func (auo *AgentUpdateOne) ClearFirstContact() *AgentUpdateOne {
	auo.mutation.ClearFirstContact()
	return auo
}

// SetLastContact sets the "last_contact" field.
func (auo *AgentUpdateOne) SetLastContact(t time.Time) *AgentUpdateOne {
	auo.mutation.SetLastContact(t)
	return auo
}

// SetNillableLastContact sets the "last_contact" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableLastContact(t *time.Time) *AgentUpdateOne {
	if t != nil {
		auo.SetLastContact(*t)
	}
	return auo
}

// ClearLastContact clears the value of the "last_contact" field.
func (auo *AgentUpdateOne) ClearLastContact() *AgentUpdateOne {
	auo.mutation.ClearLastContact()
	return auo
}

// SetEnabled sets the "enabled" field.
func (auo *AgentUpdateOne) SetEnabled(b bool) *AgentUpdateOne {
	auo.mutation.SetEnabled(b)
	return auo
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableEnabled(b *bool) *AgentUpdateOne {
	if b != nil {
		auo.SetEnabled(*b)
	}
	return auo
}

// SetVnc sets the "vnc" field.
func (auo *AgentUpdateOne) SetVnc(s string) *AgentUpdateOne {
	auo.mutation.SetVnc(s)
	return auo
}

// SetNillableVnc sets the "vnc" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableVnc(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetVnc(*s)
	}
	return auo
}

// ClearVnc clears the value of the "vnc" field.
func (auo *AgentUpdateOne) ClearVnc() *AgentUpdateOne {
	auo.mutation.ClearVnc()
	return auo
}

// SetComputerID sets the "computer" edge to the Computer entity by ID.
func (auo *AgentUpdateOne) SetComputerID(id int) *AgentUpdateOne {
	auo.mutation.SetComputerID(id)
	return auo
}

// SetNillableComputerID sets the "computer" edge to the Computer entity by ID if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableComputerID(id *int) *AgentUpdateOne {
	if id != nil {
		auo = auo.SetComputerID(*id)
	}
	return auo
}

// SetComputer sets the "computer" edge to the Computer entity.
func (auo *AgentUpdateOne) SetComputer(c *Computer) *AgentUpdateOne {
	return auo.SetComputerID(c.ID)
}

// SetOperatingsystemID sets the "operatingsystem" edge to the OperatingSystem entity by ID.
func (auo *AgentUpdateOne) SetOperatingsystemID(id int) *AgentUpdateOne {
	auo.mutation.SetOperatingsystemID(id)
	return auo
}

// SetNillableOperatingsystemID sets the "operatingsystem" edge to the OperatingSystem entity by ID if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableOperatingsystemID(id *int) *AgentUpdateOne {
	if id != nil {
		auo = auo.SetOperatingsystemID(*id)
	}
	return auo
}

// SetOperatingsystem sets the "operatingsystem" edge to the OperatingSystem entity.
func (auo *AgentUpdateOne) SetOperatingsystem(o *OperatingSystem) *AgentUpdateOne {
	return auo.SetOperatingsystemID(o.ID)
}

// SetSystemupdateID sets the "systemupdate" edge to the SystemUpdate entity by ID.
func (auo *AgentUpdateOne) SetSystemupdateID(id int) *AgentUpdateOne {
	auo.mutation.SetSystemupdateID(id)
	return auo
}

// SetNillableSystemupdateID sets the "systemupdate" edge to the SystemUpdate entity by ID if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableSystemupdateID(id *int) *AgentUpdateOne {
	if id != nil {
		auo = auo.SetSystemupdateID(*id)
	}
	return auo
}

// SetSystemupdate sets the "systemupdate" edge to the SystemUpdate entity.
func (auo *AgentUpdateOne) SetSystemupdate(s *SystemUpdate) *AgentUpdateOne {
	return auo.SetSystemupdateID(s.ID)
}

// SetAntivirusID sets the "antivirus" edge to the Antivirus entity by ID.
func (auo *AgentUpdateOne) SetAntivirusID(id int) *AgentUpdateOne {
	auo.mutation.SetAntivirusID(id)
	return auo
}

// SetNillableAntivirusID sets the "antivirus" edge to the Antivirus entity by ID if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableAntivirusID(id *int) *AgentUpdateOne {
	if id != nil {
		auo = auo.SetAntivirusID(*id)
	}
	return auo
}

// SetAntivirus sets the "antivirus" edge to the Antivirus entity.
func (auo *AgentUpdateOne) SetAntivirus(a *Antivirus) *AgentUpdateOne {
	return auo.SetAntivirusID(a.ID)
}

// AddLogicaldiskIDs adds the "logicaldisks" edge to the LogicalDisk entity by IDs.
func (auo *AgentUpdateOne) AddLogicaldiskIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.AddLogicaldiskIDs(ids...)
	return auo
}

// AddLogicaldisks adds the "logicaldisks" edges to the LogicalDisk entity.
func (auo *AgentUpdateOne) AddLogicaldisks(l ...*LogicalDisk) *AgentUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return auo.AddLogicaldiskIDs(ids...)
}

// AddAppIDs adds the "apps" edge to the App entity by IDs.
func (auo *AgentUpdateOne) AddAppIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.AddAppIDs(ids...)
	return auo
}

// AddApps adds the "apps" edges to the App entity.
func (auo *AgentUpdateOne) AddApps(a ...*App) *AgentUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.AddAppIDs(ids...)
}

// AddMonitorIDs adds the "monitors" edge to the Monitor entity by IDs.
func (auo *AgentUpdateOne) AddMonitorIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.AddMonitorIDs(ids...)
	return auo
}

// AddMonitors adds the "monitors" edges to the Monitor entity.
func (auo *AgentUpdateOne) AddMonitors(m ...*Monitor) *AgentUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return auo.AddMonitorIDs(ids...)
}

// AddShareIDs adds the "shares" edge to the Share entity by IDs.
func (auo *AgentUpdateOne) AddShareIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.AddShareIDs(ids...)
	return auo
}

// AddShares adds the "shares" edges to the Share entity.
func (auo *AgentUpdateOne) AddShares(s ...*Share) *AgentUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return auo.AddShareIDs(ids...)
}

// AddPrinterIDs adds the "printers" edge to the Printer entity by IDs.
func (auo *AgentUpdateOne) AddPrinterIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.AddPrinterIDs(ids...)
	return auo
}

// AddPrinters adds the "printers" edges to the Printer entity.
func (auo *AgentUpdateOne) AddPrinters(p ...*Printer) *AgentUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return auo.AddPrinterIDs(ids...)
}

// AddNetworkadapterIDs adds the "networkadapters" edge to the NetworkAdapter entity by IDs.
func (auo *AgentUpdateOne) AddNetworkadapterIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.AddNetworkadapterIDs(ids...)
	return auo
}

// AddNetworkadapters adds the "networkadapters" edges to the NetworkAdapter entity.
func (auo *AgentUpdateOne) AddNetworkadapters(n ...*NetworkAdapter) *AgentUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return auo.AddNetworkadapterIDs(ids...)
}

// AddDeploymentIDs adds the "deployments" edge to the Deployment entity by IDs.
func (auo *AgentUpdateOne) AddDeploymentIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.AddDeploymentIDs(ids...)
	return auo
}

// AddDeployments adds the "deployments" edges to the Deployment entity.
func (auo *AgentUpdateOne) AddDeployments(d ...*Deployment) *AgentUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return auo.AddDeploymentIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (auo *AgentUpdateOne) Mutation() *AgentMutation {
	return auo.mutation
}

// ClearComputer clears the "computer" edge to the Computer entity.
func (auo *AgentUpdateOne) ClearComputer() *AgentUpdateOne {
	auo.mutation.ClearComputer()
	return auo
}

// ClearOperatingsystem clears the "operatingsystem" edge to the OperatingSystem entity.
func (auo *AgentUpdateOne) ClearOperatingsystem() *AgentUpdateOne {
	auo.mutation.ClearOperatingsystem()
	return auo
}

// ClearSystemupdate clears the "systemupdate" edge to the SystemUpdate entity.
func (auo *AgentUpdateOne) ClearSystemupdate() *AgentUpdateOne {
	auo.mutation.ClearSystemupdate()
	return auo
}

// ClearAntivirus clears the "antivirus" edge to the Antivirus entity.
func (auo *AgentUpdateOne) ClearAntivirus() *AgentUpdateOne {
	auo.mutation.ClearAntivirus()
	return auo
}

// ClearLogicaldisks clears all "logicaldisks" edges to the LogicalDisk entity.
func (auo *AgentUpdateOne) ClearLogicaldisks() *AgentUpdateOne {
	auo.mutation.ClearLogicaldisks()
	return auo
}

// RemoveLogicaldiskIDs removes the "logicaldisks" edge to LogicalDisk entities by IDs.
func (auo *AgentUpdateOne) RemoveLogicaldiskIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.RemoveLogicaldiskIDs(ids...)
	return auo
}

// RemoveLogicaldisks removes "logicaldisks" edges to LogicalDisk entities.
func (auo *AgentUpdateOne) RemoveLogicaldisks(l ...*LogicalDisk) *AgentUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return auo.RemoveLogicaldiskIDs(ids...)
}

// ClearApps clears all "apps" edges to the App entity.
func (auo *AgentUpdateOne) ClearApps() *AgentUpdateOne {
	auo.mutation.ClearApps()
	return auo
}

// RemoveAppIDs removes the "apps" edge to App entities by IDs.
func (auo *AgentUpdateOne) RemoveAppIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.RemoveAppIDs(ids...)
	return auo
}

// RemoveApps removes "apps" edges to App entities.
func (auo *AgentUpdateOne) RemoveApps(a ...*App) *AgentUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.RemoveAppIDs(ids...)
}

// ClearMonitors clears all "monitors" edges to the Monitor entity.
func (auo *AgentUpdateOne) ClearMonitors() *AgentUpdateOne {
	auo.mutation.ClearMonitors()
	return auo
}

// RemoveMonitorIDs removes the "monitors" edge to Monitor entities by IDs.
func (auo *AgentUpdateOne) RemoveMonitorIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.RemoveMonitorIDs(ids...)
	return auo
}

// RemoveMonitors removes "monitors" edges to Monitor entities.
func (auo *AgentUpdateOne) RemoveMonitors(m ...*Monitor) *AgentUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return auo.RemoveMonitorIDs(ids...)
}

// ClearShares clears all "shares" edges to the Share entity.
func (auo *AgentUpdateOne) ClearShares() *AgentUpdateOne {
	auo.mutation.ClearShares()
	return auo
}

// RemoveShareIDs removes the "shares" edge to Share entities by IDs.
func (auo *AgentUpdateOne) RemoveShareIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.RemoveShareIDs(ids...)
	return auo
}

// RemoveShares removes "shares" edges to Share entities.
func (auo *AgentUpdateOne) RemoveShares(s ...*Share) *AgentUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return auo.RemoveShareIDs(ids...)
}

// ClearPrinters clears all "printers" edges to the Printer entity.
func (auo *AgentUpdateOne) ClearPrinters() *AgentUpdateOne {
	auo.mutation.ClearPrinters()
	return auo
}

// RemovePrinterIDs removes the "printers" edge to Printer entities by IDs.
func (auo *AgentUpdateOne) RemovePrinterIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.RemovePrinterIDs(ids...)
	return auo
}

// RemovePrinters removes "printers" edges to Printer entities.
func (auo *AgentUpdateOne) RemovePrinters(p ...*Printer) *AgentUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return auo.RemovePrinterIDs(ids...)
}

// ClearNetworkadapters clears all "networkadapters" edges to the NetworkAdapter entity.
func (auo *AgentUpdateOne) ClearNetworkadapters() *AgentUpdateOne {
	auo.mutation.ClearNetworkadapters()
	return auo
}

// RemoveNetworkadapterIDs removes the "networkadapters" edge to NetworkAdapter entities by IDs.
func (auo *AgentUpdateOne) RemoveNetworkadapterIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.RemoveNetworkadapterIDs(ids...)
	return auo
}

// RemoveNetworkadapters removes "networkadapters" edges to NetworkAdapter entities.
func (auo *AgentUpdateOne) RemoveNetworkadapters(n ...*NetworkAdapter) *AgentUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return auo.RemoveNetworkadapterIDs(ids...)
}

// ClearDeployments clears all "deployments" edges to the Deployment entity.
func (auo *AgentUpdateOne) ClearDeployments() *AgentUpdateOne {
	auo.mutation.ClearDeployments()
	return auo
}

// RemoveDeploymentIDs removes the "deployments" edge to Deployment entities by IDs.
func (auo *AgentUpdateOne) RemoveDeploymentIDs(ids ...int) *AgentUpdateOne {
	auo.mutation.RemoveDeploymentIDs(ids...)
	return auo
}

// RemoveDeployments removes "deployments" edges to Deployment entities.
func (auo *AgentUpdateOne) RemoveDeployments(d ...*Deployment) *AgentUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return auo.RemoveDeploymentIDs(ids...)
}

// Where appends a list predicates to the AgentUpdate builder.
func (auo *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Agent entity.
func (auo *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AgentUpdateOne) check() error {
	if v, ok := auo.mutation.Os(); ok {
		if err := agent.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`openuem_ent: validator failed for field "Agent.os": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Hostname(); ok {
		if err := agent.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`openuem_ent: validator failed for field "Agent.hostname": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Version(); ok {
		if err := agent.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`openuem_ent: validator failed for field "Agent.version": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (auo *AgentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AgentUpdateOne {
	auo.modifiers = append(auo.modifiers, modifiers...)
	return auo
}

func (auo *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`openuem_ent: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("openuem_ent: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Os(); ok {
		_spec.SetField(agent.FieldOs, field.TypeString, value)
	}
	if value, ok := auo.mutation.Hostname(); ok {
		_spec.SetField(agent.FieldHostname, field.TypeString, value)
	}
	if value, ok := auo.mutation.Version(); ok {
		_spec.SetField(agent.FieldVersion, field.TypeString, value)
	}
	if value, ok := auo.mutation.IP(); ok {
		_spec.SetField(agent.FieldIP, field.TypeString, value)
	}
	if value, ok := auo.mutation.FirstContact(); ok {
		_spec.SetField(agent.FieldFirstContact, field.TypeTime, value)
	}
	if auo.mutation.FirstContactCleared() {
		_spec.ClearField(agent.FieldFirstContact, field.TypeTime)
	}
	if value, ok := auo.mutation.LastContact(); ok {
		_spec.SetField(agent.FieldLastContact, field.TypeTime, value)
	}
	if auo.mutation.LastContactCleared() {
		_spec.ClearField(agent.FieldLastContact, field.TypeTime)
	}
	if value, ok := auo.mutation.Enabled(); ok {
		_spec.SetField(agent.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := auo.mutation.Vnc(); ok {
		_spec.SetField(agent.FieldVnc, field.TypeString, value)
	}
	if auo.mutation.VncCleared() {
		_spec.ClearField(agent.FieldVnc, field.TypeString)
	}
	if auo.mutation.ComputerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.ComputerTable,
			Columns: []string{agent.ComputerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(computer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.ComputerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.ComputerTable,
			Columns: []string{agent.ComputerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(computer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.OperatingsystemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.OperatingsystemTable,
			Columns: []string{agent.OperatingsystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatingsystem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.OperatingsystemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.OperatingsystemTable,
			Columns: []string{agent.OperatingsystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatingsystem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.SystemupdateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.SystemupdateTable,
			Columns: []string{agent.SystemupdateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemupdate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.SystemupdateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.SystemupdateTable,
			Columns: []string{agent.SystemupdateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemupdate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.AntivirusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.AntivirusTable,
			Columns: []string{agent.AntivirusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(antivirus.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.AntivirusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.AntivirusTable,
			Columns: []string{agent.AntivirusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(antivirus.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.LogicaldisksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.LogicaldisksTable,
			Columns: []string{agent.LogicaldisksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logicaldisk.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedLogicaldisksIDs(); len(nodes) > 0 && !auo.mutation.LogicaldisksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.LogicaldisksTable,
			Columns: []string{agent.LogicaldisksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logicaldisk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.LogicaldisksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.LogicaldisksTable,
			Columns: []string{agent.LogicaldisksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logicaldisk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.AppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AppsTable,
			Columns: []string{agent.AppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedAppsIDs(); len(nodes) > 0 && !auo.mutation.AppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AppsTable,
			Columns: []string{agent.AppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.AppsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AppsTable,
			Columns: []string{agent.AppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.MonitorsTable,
			Columns: []string{agent.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedMonitorsIDs(); len(nodes) > 0 && !auo.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.MonitorsTable,
			Columns: []string{agent.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.MonitorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.MonitorsTable,
			Columns: []string{agent.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SharesTable,
			Columns: []string{agent.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedSharesIDs(); len(nodes) > 0 && !auo.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SharesTable,
			Columns: []string{agent.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SharesTable,
			Columns: []string{agent.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.PrintersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.PrintersTable,
			Columns: []string{agent.PrintersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(printer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedPrintersIDs(); len(nodes) > 0 && !auo.mutation.PrintersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.PrintersTable,
			Columns: []string{agent.PrintersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(printer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.PrintersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.PrintersTable,
			Columns: []string{agent.PrintersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(printer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.NetworkadaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.NetworkadaptersTable,
			Columns: []string{agent.NetworkadaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkadapter.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedNetworkadaptersIDs(); len(nodes) > 0 && !auo.mutation.NetworkadaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.NetworkadaptersTable,
			Columns: []string{agent.NetworkadaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkadapter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.NetworkadaptersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.NetworkadaptersTable,
			Columns: []string{agent.NetworkadaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkadapter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.DeploymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.DeploymentsTable,
			Columns: []string{agent.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedDeploymentsIDs(); len(nodes) > 0 && !auo.mutation.DeploymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.DeploymentsTable,
			Columns: []string{agent.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.DeploymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.DeploymentsTable,
			Columns: []string{agent.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(auo.modifiers...)
	_node = &Agent{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
